import type { Metadata } from 'next'
import { Figtree, Inter } from 'next/font/google'
import './globals.css'

const figTree = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${figTree.className} antialiased`}>{children}</body>
    </html>
  )
}
